module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./app/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        basic_0: "#FFFEFC",
        basic_1: "#FFF9EF",
        basic_2: "#FFF6E6",
        basic_3: "#FFF3E0",
        basic_4: "#FFF0D7",
        basic_5: "#FFECCD",
        basic_6: "#FFE8C1",
        basic_7: "#FFE3B4",
        black: "#1F1F1F",
        gray_0: "#E8E9E8",
        gray_1: "#DBDBDB",
        gray_2: "#C1C1C1",
        gray_3: "#AAAAAA",
        gray_4: "#7F7F7F",
        gray_5: "#5C5C5C",
        orange_0: "#FFECD9",
        orange_1: "#FFDDBC",
        orange_2: "#FFC891",
        orange_3: "#FFBE7C",
        orange_4: "#FFB062",
        orange_5: "#FFA851",
        green_1: "#E9FBF2",
        green_2: "#B9F4D6",
        green_3: "#6ADCA3",
        green_4: "#007560",
      },
    },
  },
  plugins: [],
};
